version: '3.2'

services:
  master:
    image: pikachust8811/all-in-one:1.1.0
    tty: true
    ports:
      - "18080:18080"
      - "4040-4049:4040-4049"
      - "50070:50070"
      - "50075:50075"
      - "7077:7077"
      - "8088:8088"
      - "8888:8888"
      - "9000:9000"
    environment:
      - MASTER_HOSTNAME=master
      - JUPYTER_AUTH_TOKEN=password
    networks:
      - spark_network
    volumes:
      - type: volume
        source: jupyter_data
        target: /data

volumes:
  jupyter_data:

networks:
  spark_network:
    driver: "bridge"
