version: '3.2'

services:
  master:
    image: pikachust8811/yarn-spark:h2.9.0-s2.3.0
    ports:
      - "50070:50070"
      - "50075:50075"
      - "8088:8088"
      - "18080:18080"
    environment:
      - NODE_TYPE=master
    tty: true
    networks:
      - yarn_network
    volumes:
      - type: volume
        source: master_data
        target: /data

  slave-1:
    image: pikachust8811/yarn-spark:h2.9.0-s2.3.0
    environment:
      - NODE_TYPE=slave
    tty: true
    networks:
      - yarn_network
    volumes:
      - type: volume
        source: slave_1_data
        target: /data

  # slave-2:
  #   image: pikachust8811/yarn-spark:h2.9.0-s2.3.0
  #   environment:
  #     - NODE_TYPE=slave
  #   tty: true
  #   networks:
  #     - yarn_network
  #   volumes:
  #     - type: volume
  #       source: slave_2_data
  #       target: /data

  driver:
    image: pikachust8811/yarn-spark:h2.9.0-s2.3.0
    tty: true
    networks:
      - yarn_network

volumes:
  master_data:
  slave_1_data:
  # slave_2_data:

networks:
  yarn_network:
    driver: "bridge"
