version: '3.2'

services:
  master:
    image: pikachust8811/docker-spark:1.0.4
    tty: true
    ports:
      - "8888:8888"
      - "50070:50070"
      - "50075:50075"
      - "8088:8088"
      - "18080:18080"
      - "7077:7077"
      - "31000-31004:31000-31004"
      - "31032-31036:31032-31036"
    environment:
      - HOST_IP=192.168.15.244
      - MASTER_HOSTNAME=master
      - JUPYTER_AUTH_TOKEN=password
    networks:
      - spark_network
    volumes:
      - type: volume
        source: jupyter_data
        target: /data

volumes:
  jupyter_data:

networks:
  spark_network:
    driver: "bridge"
